# Generated by Django 6.1.1 on 2026-09-16 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('custom', 'Custom')], db_index=True, max_length=32, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('model_name', models.CharField(blank=True, db_index=True, help_text='Class name of the affected model (e.g., "Product").', max_length=100, verbose_name='Model Name')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object at event time.', max_length=255, verbose_name='Object Representation')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, help_text='For custom events: {"message_id": "...", "params": {...}}', null=True, verbose_name='Metadata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='drf_audit_l_user_id_6ad51a_idx'), models.Index(fields=['action', '-timestamp'], name='drf_audit_l_action_fd48a7_idx'), models.Index(fields=['model_name', 'object_id'], name='drf_audit_l_model_n_c094b7_idx')],
            },
        ),
    ]
